spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-service
  profiles:
    active: dev, auth
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8082