spring:
  application:
    name: FoxWear
  profiles:
    active: auth, dev
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

springdoc:
  swagger-ui:
    path: /swagger

server:
  port: 8080