spring:
  application:
    name: FoxWear

  datasource:
    username: rgb
    password: 1234
    url: jdbc:postgresql://localhost:5432/foxwear_db
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false


springdoc:
  swagger-ui:
    path: /swagger

server:
  port: 8080