spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dynamic_db
    username: foxwear
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

aws:
  s3:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
    region: "eu-north-1"
    bucket-name: "foxwear-images"